# Übung 2.1 

In dieser Übung werden wir uns mit wichtigen Software-Werkzeugen für Data Science vertraut machen. In diesem Notebook finden Sie Übung 2.1, die sich mit Numpy beschäftigt. Übung 2.2 (Pandas) finden Sie bei ILIAs.

Diese Übungen dienen dazu, Sie auf verschiedene Aspekte der in den kommenden Wochen in den Übungen genutzten Werkzeuge aufmerksam zu machen.

* Wenn Sie in Ihrem bisherigen Studienverlauf noch nicht viel mit Python zu tun hatten, schauen Sie doch gerne einmal bei ILIAS unter "Lernressourcen" nach. Ich habe Ihnen dort Inhalte hinterlegt, die Sie nutzen können, um sich im Selbststudium mit Python vertrauter zu machen.

## 2.1.1 Shapes und Co.

Bei vielen Data Science Projekten werden Daten zunächst zugänglich gemacht, so dass sie als Numpy Arrays vorliegen. Das Verständnis von *Shapes* solcher Arrays ist eine wichtige Voraussetzung für eine produktive Arbeit mit diesen Datenstrukturen.

Nehmen Sie die Folien zur heutigen Vorlesung zur Hand.

**Ihre Aufgaben**

(1) Betrachten Sie den untenstehenden Code. Beantworten Sie: Welchen [Shape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html) hat das Numpy Array `a`? 

In [5]:
import numpy as np
a = np.array([5, 10, 15, 20])

print(f"a:\t{a}, shape of a:\t{a.shape}")

a:	[ 5 10 15 20], shape of a:	(4,)


> Shape: (4,)

(2) Lässt sich das Array `a` als (mathematischen) Vektor interpretieren? Wenn `a` ein Vektor ist, können Sie ihn [transponieren](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.T.html)?

a shape: (4,) => besitzt nur eine Dimension (1D-Array), es ist strenggenommen kein Vektor, da die zweite Dimension (auch wenn diese =1 ist) fehlt.
Transponiert man a so wie es ist, ändert sich nichts. Um zwischen Spalten- und Zeilenvektoren zu transponieren, muss die fehlende Dimension hinzugefügt werden (reshape).

In [4]:
# missing dim is inferred when providing '-1')
a_reshaped = a.reshape(-1, a.shape[0])
print(f"a reshaped:\t{a_reshaped}, new shape:\t{a_reshaped.shape}")
a_reshaped_transposed = a_reshaped.T
print(f"a reshaped, transposed:\t{a_reshaped_transposed}, new shape:\t{a_reshaped_transposed.shape}")

a reshaped:	[[ 5 10 15 20]], new shape:	(1, 4)
a reshaped, transposed:	[[ 5]
 [10]
 [15]
 [20]], new shape:	(4, 1)


Durch reshape(-1, a.shape(0)) wird ein 2D-Array erzeugt, a ist nun ein Zeilenvektor. Transponieren überführt a dann in einen Spaltenvektor.

(3) Betrachten Sie das unten stehende Array `b`. Erzeugen Sie aus `b` bitte zwei neue Arrays `c` und `d`: `c` soll ein Spaltenvektor sein, und `d` soll ein Zeilenvektor sein. Wie gehen Sie vor?

In [7]:
b = np.array([2, 4, 6, 8, 10])
print(f"Shape of b:\t{b.shape}")

Shape of b:	(5,)


In [8]:
c = b.reshape(b.shape[0], -1)
d = c.T
print(f"c:\t{c}, shape of c:\t{c.shape}")
print(f"d:\t{d}, shape of d:\t{d.shape}")

c:	[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]], shape of c:	(5, 1)
d:	[[ 2  4  6  8 10]], shape of d:	(1, 5)


Lässt sich `c` bzw. `d` transponieren? Warum?

=> Ja, c und d haben nach dem Reshape nun 2 Dimensionen, können also als Vektoren bzw. Matrizen mit einer Zeile / Spalte betrachtet werden.

(4) Betrachten Sie die dritte Zeile des unten stehenden Codes: Hat sich durch die Zeile `k[0, 1] = 10` das Array `m` geändert? Falls ja, warum? Falls nein, warum hat es sich nicht geändert?

In [11]:
k = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
# m als eine Submatrix von k: Zeilen 0-1 und Spalten 1-2 aus k nehmen
m = k[:2, 1:3]  # hier wird Basic-Indexing verwendet => erzegt eine View von k, keine Kopie!
print(f"Sub-Array m von k (View):\n{m}")
k[0, 1] = 10
print(f"k geändert:\n{k}\nm:\n{m}")

Sub-Array m von k (View):
[[2 3]
 [6 7]]
k geändert:
[[ 1 10  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
m:
[[10  3]
 [ 6  7]]


Ja, das Array m hat sich durch k[0, 1] = 10 geändert: hier wird Basic-Indexing verwendet, welches eine View von k erzeugt, keine Kopie von k.

(5) Betrachten Sie die dritte Zeile des unten stehenden Codes: Hat sich durch die Änderung des Arrays `p` der Inhalt von `q` geändert? Falls ja, warum? Falls nein, warum hat es sich nicht geändert?

In [12]:
p = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
# Selektion: Zeilen 1 und 2 aus p von Spalte 0 nehmen
q = p[[1, 2], 0]  # Verwendung von Advanced-Indexing => q ist eine Kopie der entsprechenden Selektion von p-Elementen
print(f"p:\n{p}\nq:\n{q}")
# Änderung des Elementwertes an der Stelle (1,0): Zeilenidx = 1, Spaltenidx = 0 => 5 ==> 25
p[1, 0] = 25
print(f"p:\n{p}\nq:\n{q}")

p:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
q:
[5 9]
p:
[[ 1  2  3  4]
 [25  6  7  8]
 [ 9 10 11 12]]
q:
[5 9]


Durch die Änderung des Arrays p hat sich der Inhalt von q nicht geändert: zur Erzeugung von q wird Advanced Indexing verwendet, wodurch eine Kopie erzeugt wird.

## 2.1.2 Broadcasting - Teil 1

Nehmen Sie sich die Folien zur heutigen Vorlesung zur Hand. Unten sehen Sie eine Operation mit zwei Numpy Arrays `a` und `b`.

**Ihre Aufgaben**

(1) Betrachten Sie die unten stehende Code-Zelle. Welchen Shape (Anzahl Zeilen, Anzahl Spalten) wird das Numpy Array `c` erhalten? 

  * Tragen Sie ihre Voraussage in die Variable `shape` ein. 
  * Begründen Sie Ihre Vorhersage mit den drei Broadcasting Regeln aus der Vorlesung.
  * Berechnen Sie auf Papier das zu erwartende Ergebnis. Tragen Sie es als Numpy Array in die Variable `ergebnis` ein.
  * Führen Sie dann jeweils die Zelle aus, um zu schauen, ob Sie richtig lagen.

In [13]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b
print(c.shape)

# Ihre Vorhersagen
shape = (3,)

# ergebnis: a und b werden elementweise addiert
ergebnis = np.array([5, 7, 9])

print('{}\n'.format('Shape korrekt.' if np.all(shape==c.shape) else 'Shape nicht korrekt.'))
print('{}\n'.format('Ergebnis korrekt.' if np.array_equal(ergebnis, c) else 'Ergebnis nicht korrekt.'))

(3,)
Shape korrekt.

Ergebnis korrekt.



(2) Betrachten Sie die unten stehende Code-Zelle. Welchen Shape (Anzahl Zeilen, Anzahl Spalten) wird das Numpy Array `c` erhalten? 

  * Tragen Sie ihre Voraussage in die Variable `shape` ein. 
  * Begründen Sie Ihre Vorhersage mit den drei Broadcasting Regeln aus der Vorlesung.
  * Berechnen Sie auf Papier das zu erwartende Ergebnis. Tragen Sie es als Numpy Array in die Variable `ergebnis` ein.
  * Führen Sie dann jeweils die Zelle aus, um zu schauen, ob Sie richtig lagen.

**Rules of Broadcasting:**
1. The two arrays differ in their number of dimensions The Shape of the array with fewer dims is padded with ones on its left (:= leading) side.
2. The shape of the two arrays does not match in ANY dimension The array with shape equal to 1 in that dimension is stretched to match the other shape,
3. If in any dim the sizes disagree and neither is equal to 1 => Error-Message

In [15]:
a = np.array([1, 2, 3]) #1x3
b = np.array([4, 5, 6])[:, np.newaxis] #3x1

c = a + b

shape = (3, 3) # Ihre Vorhersage
ergebnis = np.array([[5, 6, 7], [6, 7, 8], [7, 8, 9]])

print('{}\n'.format('Shape Korrekt.' if np.all(shape==c.shape) else 'Shape nicht korrekt.'))
print('{}\n'.format('Ergebnis korrekt.' if np.array_equal(ergebnis, c) else 'Ergebnis nicht korrekt.'))

Shape Korrekt.

Ergebnis korrekt.



Zur Aufgabe: Hier stimmen a und b in ihrem Shape von vornherein überein, es muss also kein Padding / Stretching stattfinden. Es werden einfach die a_i und b_i elementweise addiert (ufunc).

(3) Betrachten Sie die unten stehende Code-Zelle. Welchen Shape (Anzahl Zeilen, Anzahl Spalten) wird das Numpy Array `c` erhalten? 

  * Tragen Sie ihre Voraussage in die Variable `shape` ein. 
  * Begründen Sie Ihre Vorhersage mit den drei Broadcasting Regeln aus der Vorlesung.
  * Berechnen Sie auf Papier das zu erwartende Ergebnis. Tragen Sie es als Numpy Array in die Variable `ergebnis` ein.
  * Führen Sie dann jeweils die Zelle aus, um zu schauen, ob Sie richtig lagen.

In [17]:
a = np.array([[1, 0, 0], [0, 0, 2]])
b = np.ones(12).reshape((4, 1, 3))
c = a * b

shape = (4, 2, 3) # Ihre Vorhersage
# pad a
a_padded = np.reshape(a, (1, 2, 3))
a_stretched = np.array([*a_padded, *a_padded, *a_padded, *a_padded])  # * resolves the arg
# print(a_stretched)
ergebnis = np.array(a_stretched) # sobald die dims alle passen wird elementweise multipliziert;
# b ist eine komplette 1er Matrix => also überall nur mult. mit 1

print('{}\n'.format('Shape korrekt.' if np.all(shape==c.shape) else 'Shape nicht korrekt.'))
print('{}\n'.format('Ergebnis korrekt.' if np.array_equal(ergebnis, c) else 'Ergebnis nicht korrekt.'))

Shape korrekt.

Ergebnis korrekt.



(a) shape von a: (2,3), shape von b: (4,1,3) => die shapes passen nicht zueinander
(b) 1. Padding von a => (1,2,3) ist neuer shape
(c) 2. Stretching von a und b => a: gedankliches Hinzufügen (vertikal) von [[1,0,0],[0,0,2]], 3x => “shape”: (4,2,3) b: gedankliches Hinzufügen (horizontal) von [1,1,1,1,1,1,1,1,1,1,1,1], 1x => “shape”: (4,2,3)
(d) shapes von a und b stimmen un überein => Anwendung der ufunc * elementweise auf a_ij und b_ij

## 2.1.3 Broadcasting Teil 2

Ein häufiger Vorverarbeitungsschritt, der Ihnen in verschiedenen Data Science Projekten begegnen wird, ist die Normierung von Daten. Häufig werden dabei Datensätze, z.B. Zeitreihen, auf Mittelwert $0$ und Standardabweichung $1$ normiert. Dieser Vorgang wird auch *z-scoring* (oder: *Standardisierung*) genannt:

Sei $x_i$ der $i$-te Datenpunkt einer Zeitreihe. Dann ist der z-score dieses Datenpunkts definiert als

$$\tilde{x}_i = \frac{x_i - \bar{x}}{\sigma},$$ 

wobei $\bar{x}$ der Mittelwert sowie $\sigma$ die Standardabweichung der Zeitreihe bezeichnen.

Das in der unten stehenden Code-Zelle definierte Numpy Array `X` enthält 5 Zeitreihen (Spalten) mit je 30 Einträgen (Zeilen). 

* Nutzen Sie Broadcasting sowie [np.mean](https://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html) und [np.std](https://docs.scipy.org/doc/numpy/reference/generated/numpy.std.html), um die Zeitreihen auf Mittelwert 0 und Varianz 1 zu normieren. Die transformierten Zeitreihen sollen im Numpy Array `Y` gespeichert werden. Dabei schreiben Sie nur eine Zeile Code, um die Zeitreihen zu transformieren.
* Beachten Sie das `axis` Argument bei `np.mean` und `np.std`.

In [19]:
import numpy as np
np.random.seed(0)

X = np.random.random((30, 5))

# Ihr Ergebnis:
Y = (X-np.mean(X, axis=0))/np.std(X, axis=0)
print(f"Ergebnis Y => Standardization on each col of the array:\n{Y}")
# Test if e.g. mean of 1st col = 1
print(f"Test:\nMean of first column = {np.mean(Y[:, [0]])}\nVAR of first column = {np.var(Y[:, [0]])}")

Ergebnis Y => Standardization on each col of the array:
[[ 0.16740311  0.99146058  0.26566035 -0.19189575 -0.10401878]
 [ 0.55391341 -0.15048406  1.19070719  1.37326414 -0.23972755]
 [ 1.13451499  0.22511946  0.15453418  1.23099463 -1.29401013]
 [-1.67071577 -1.86737303  1.00137287  0.67994818  1.40231461]
 [ 1.8785996   1.33687639 -0.18655411  0.68881496 -1.13459362]
 [ 0.53013254 -1.36084517  1.36001366 -0.27798696 -0.13436721]
 [-0.96432242  1.23434539 -0.20361099 -0.10387638 -1.47032689]
 [ 0.44140643  0.56737441  0.31101693  1.29883439  0.76721883]
 [-0.58628567 -0.15276817  0.56930829 -2.00327065  0.71641712]
 [ 0.65242656 -1.08511345 -1.25097251 -1.04946742 -0.30631341]
 [ 0.25253703 -0.14631163  1.49990208 -1.84697374 -0.82883566]
 [-1.37537957  0.73608391 -0.85291057 -0.48555474 -0.7088681 ]
 [-1.38469563 -1.49650412  0.43711227 -1.71190993 -0.87032586]
 [-0.54958864  1.42669551 -1.35283637  0.90340231 -1.20943159]
 [ 1.87000439 -0.02269919  1.4627326   0.03220936  0.96107412]

## 2.1.4 Advanced Indexing

Nehmen Sie sich die Folien der heutigen Vorlesung zur Hand. In diesem Übungsteil geht es darum, Sie mit *Advanced Indexing* in Numpy Arrays vertraut zu machen.

**Ihre Aufgaben**

(1) Betrachten Sie den unten stehenden Code-Zellen.
* Tragen Sie in der Variable `vorhersage` ein, welches Array Sie in Variable `y` erwarten.
* Prüfen Sie durch Ausführen des Codes, ob Ihre Vorhersage richtig war.
* Beantworten Sie die Frage: Wodurch wird der Shape des Arrays `y` bestimmt?

In [20]:
import numpy as np 

x = np.array([[1, 2], [3, 4], [5, 6]]) 
y = x[[0,1,2], [0,1,0]] 

vorhersage = np.array([1, 4, 5]) # Ihre Vorhersage

print('{}\n'.format('Ergebnis korrekt.' if np.array_equal(vorhersage, y) else 'Ergebnis nicht korrekt.'))

Ergebnis korrekt.



=> Der Shape des Ergebnisarrays wird durch das "Indexarray" bestimmt => shape von 'row' (= [0,1,2]): (3,), shape von 'col' (=[0,1,0]): (3,) (beide shapes stimmen überein)
=> Zur Indizierung werden hier für die Zeilen- und Spaltenelemente jeweils Arrays übergeben
=> daraus wird gedanklich eine Indexmatrix gebaut, indem elementweise die zu selektierenden Elemente in Tupel (row_ij, col_ij) zusammengepackt werden:
    $idx = \begin{pmatrix} (0,0) &(1,1) &(2,0)\end{pmatrix}$
=> da row und col hier den gleichen shape haben, ist auch die "indexmatrix" von diesem shape und somit dann auch das Ergebnis

(2) Betrachten Sie den unten stehenden Code-Zellen.
* Tragen Sie in der Variable `vorhersage` ein, welches Array Sie in Variable `y` erwarten.
* Prüfen Sie durch Ausführen des Codes, ob Ihre Vorhersage richtig war.
* Beantworten Sie die Frage: Wodurch wird der Shape des Arrays `y` bestimmt?

In [21]:
x = np.array([[0,  1,  2], [3,  4,  5], [6,  7,  8], [9, 10, 11]])

rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]])
y = x[rows,cols]

vorhersage = np.array([[0, 2], [9, 11]]) # Ihre Vorhersage

print('{}\n'.format('Ergebnis korrekt.' if np.array_equal(vorhersage, y) else 'Ergebnis nicht korrekt.'))

Ergebnis korrekt.



Der Shape des Ergebnisarrays wird durch das “Indexarray” bestimmt: shape von rows: (2,2), shape von cols: (2,2)
=> Zur Indizierung werden hier für die Zeilen- und Spaltenelemente jeweils Arrays übergeben; daraus wird gedanklich eine Indexmatrix gebaut, indem  elementweise die zu selektierenden Elemente in Tupel (row_ij, col_ij) zusammengepackt werden:
    $idx = \begin{pmatrix} (0,0) &(0,2)\\ (3,0) &(0,2)\end{pmatrix}$
Da row und col hier den gleichen shape haben, ist auch die “indexmatrix” von diesem shape und somit dann auch das Ergebnis.


(3) Betrachten Sie den unten stehenden Code-Zellen.
* Tragen Sie in der Variable `vorhersage` ein, welches Array Sie in Variable `y` erwarten.
* Prüfen Sie durch Ausführen des Codes, ob Ihre Vorhersage richtig war.
* Beantworten Sie die Frage: Wodurch wird der Shape des Arrays `y` bestimmt?

In [22]:
x = np.array([[0, 1, 2],[3, 4, 5],[6, 7, 8],[9, 10, 11]]) 

y = x[1:4,[1,2]] # Kombination von Slicing und Advanced Indexing

vorhersage = np.array([[4, 5], [7, 8], [10, 11]]) # Ihre Vorhersage

print('{}\n'.format('Ergebnis korrekt.' if np.array_equal(vorhersage, y) else 'Ergebnis nicht korrekt.'))

Ergebnis korrekt.



Der Shape von y wird durch die Kombination von Slicing und Advanced Indexing bestimmt: die Anzahl der Zeilen wird durch Slicing von x (Zeilen 1-4 (exkl.)) bestimmt, die Anzahl der Spalten durch Advanced Indexing (jeweils Spalte mit Idx 1 und 2). => Shape von y: (3,2)